// src/components/DetailModal.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Participant, Project } from '../types'
import {
  getProfilePictureUrl,
  getInitials,
  getProjectsForParticipant,
  getParticipantsForProject
} from '../utils/helpers'

const props = defineProps<{
  activeModalType: 'person' | 'project' | null
  activeItem: Participant | Project | null
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'showPerson', person: Participant): void
  (e: 'showProject', project: Project): void
}>()

const activeParticipant = computed(() => {
  return props.activeModalType === 'person' ? props.activeItem as Participant : null
})

const activeProject = computed(() => {
  return props.activeModalType === 'project' ? props.activeItem as Project : null
})
</script>

<template>
  <Transition name="fade-blur">
    <div v-if="activeModalType" class="detail-modal-overlay" @click.self="emit('close')">
      <!-- Person Detail Modal -->
      <div
        v-if="activeModalType === 'person' && activeParticipant"
        class="detail-modal-content card border border-white border-opacity-15 rounded-4 p-4 text-start"
      >
        <div class="modal-glow-bg" :class="activeParticipant.industry === 'IT' ? 'it-glow' : 'embedded-glow'"></div>

        <button
          class="btn-close btn-close-white position-absolute top-0 end-0 m-3 shadow-none z-3"
          @click="emit('close')"
          aria-label="Close"
        ></button>

        <div class="position-relative z-2">
          <!-- Header with avatar, name, industry -->
          <div class="d-flex align-items-center gap-3 mb-4">
            <div class="position-relative flex-shrink-0" style="width: 80px; height: 80px;">
              <img
                v-if="activeParticipant.profilePicture"
                :src="getProfilePictureUrl(activeParticipant.profilePicture)"
                :alt="activeParticipant.name"
                class="rounded-circle object-fit-cover border border-white border-opacity-20 shadow"
                style="width: 80px; height: 80px;"
              />
              <div
                v-else
                class="d-flex align-items-center justify-content-center rounded-circle border border-white border-opacity-20 text-white fw-bold shadow"
                :style="
                  activeParticipant.industry === 'IT'
                    ? 'background-color: rgba(77, 163, 255, 0.1); color: #4da3ff !important; width: 80px; height: 80px; font-size: 1.5rem;'
                    : 'background-color: rgba(255, 210, 0, 0.1); color: #ffd200 !important; width: 80px; height: 80px; font-size: 1.5rem;'
                "
              >
                {{ getInitials(activeParticipant.name) }}
              </div>
            </div>
            <div>
              <h2 class="h4 fw-bold text-white mb-1 tracking-tight">{{ activeParticipant.name }}</h2>
              <span
                class="badge rounded-pill text-uppercase tracking-wider small fw-bold"
                :class="activeParticipant.industry === 'IT' ? 'bg-primary bg-opacity-25 text-cyan border border-info border-opacity-10' : 'bg-warning bg-opacity-25 text-gold border border-warning border-opacity-10'"
                style="font-size: 0.7rem;"
              >
                {{ activeParticipant.industry }} Developer
              </span>
            </div>
          </div>

          <!-- Bio -->
          <div class="mb-4">
            <h3 class="h6 uppercase-heading mb-2">Biography</h3>
            <p class="mb-0 line-height-relaxed modal-description">
              {{ activeParticipant.description }}
            </p>
          </div>

          <!-- Skills -->
          <div class="mb-4">
            <h3 class="h6 uppercase-heading mb-2">Skills &amp; Expertise</h3>
            <div class="d-flex flex-wrap gap-2">
              <span v-for="skill in activeParticipant.skills" :key="skill" class="badge-skill">
                {{ skill }}
              </span>
            </div>
          </div>

          <!-- Projects -->
          <div>
            <h3 class="h6 uppercase-heading mb-3">Assigned Projects</h3>
            <div class="d-flex flex-column gap-2">
              <div
                v-for="proj in getProjectsForParticipant(activeParticipant.name)"
                :key="proj.title"
                class="sub-card p-3 rounded-3 d-flex justify-content-between align-items-center transition-all cursor-pointer"
                @click="emit('showProject', proj)"
              >
                <div>
                  <h4 class="h6 fw-bold text-white mb-1">{{ proj.title }}</h4>
                  <span
                    class="text-uppercase tracking-wider small fw-semibold"
                    :class="proj.category.includes('IT') ? 'text-cyan' : 'text-gold'"
                    style="font-size: 0.7rem"
                  >
                    {{ proj.category }}
                  </span>
                </div>
                <button
                  class="btn btn-sm btn-outline-light-custom rounded-pill px-3 py-1 text-nowrap ms-3"
                >
                  View Project
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Project Detail Modal -->
      <div
        v-if="activeModalType === 'project' && activeProject"
        class="detail-modal-content card border border-white border-opacity-15 rounded-4 p-4 text-start"
      >
        <div class="modal-glow-bg" :class="activeProject.category.includes('IT') ? 'it-glow' : 'embedded-glow'"></div>

        <button
          class="btn-close btn-close-white position-absolute top-0 end-0 m-3 shadow-none z-3"
          @click="emit('close')"
          aria-label="Close"
        ></button>

        <div class="position-relative z-2">
          <!-- Header -->
          <div class="mb-4">
            <span
              class="badge rounded-pill text-uppercase tracking-wider small fw-bold mb-2 d-inline-block"
              :class="activeProject.category.includes('IT') ? 'bg-primary bg-opacity-25 text-cyan border border-info border-opacity-10' : 'bg-warning bg-opacity-25 text-gold border border-warning border-opacity-10'"
              style="font-size: 0.7rem;"
            >
              {{ activeProject.category }} Project
            </span>
            <h2 class="h4 fw-bold text-white mb-0 tracking-tight">{{ activeProject.title }}</h2>
          </div>

          <!-- Description -->
          <div class="mb-4">
            <h3 class="h6 uppercase-heading mb-2">Project Overview</h3>
            <p class="mb-0 line-height-relaxed modal-description">
              {{ activeProject.description }}
            </p>
          </div>

          <!-- Tech Used -->
          <div class="mb-4">
            <h3 class="h6 uppercase-heading mb-2">Technologies Used</h3>
            <div class="d-flex flex-wrap gap-2">
              <span v-for="skill in activeProject.skills" :key="skill" class="badge-skill">
                {{ skill }}
              </span>
            </div>
          </div>

          <!-- Team -->
          <div>
            <h3 class="h6 uppercase-heading mb-3">Project Team</h3>
            <div class="d-flex flex-column gap-2">
              <div
                v-for="p in getParticipantsForProject(activeProject.title)"
                :key="p.name"
                class="sub-card p-3 rounded-3 d-flex justify-content-between align-items-center transition-all cursor-pointer"
                @click="emit('showPerson', p)"
              >
                <div class="d-flex align-items-center gap-2.5">
                  <!-- Profile Picture or Initials in Project Modal -->
                  <img
                    v-if="p.profilePicture"
                    :src="getProfilePictureUrl(p.profilePicture)"
                    :alt="p.name"
                    class="rounded-circle object-fit-cover border border-white border-opacity-15"
                    style="width: 40px; height: 40px; flex-shrink: 0;"
                  />
                  <div
                    v-else
                    class="d-flex align-items-center justify-content-center rounded-circle border border-white border-opacity-10 text-white fw-bold"
                    :style="
                      p.industry === 'IT'
                        ? 'background-color: rgba(77, 163, 255, 0.1); color: #4da3ff !important; width: 40px; height: 40px; font-size: 0.9rem; flex-shrink: 0;'
                        : 'background-color: rgba(255, 210, 0, 0.1); color: #ffd200 !important; width: 40px; height: 40px; font-size: 0.9rem; flex-shrink: 0;'
                    "
                  >
                    {{ getInitials(p.name) }}
                  </div>
                  <div>
                    <h4 class="h6 fw-bold text-white mb-0">{{ p.name }}</h4>
                    <span
                      class="text-uppercase tracking-wider small fw-semibold"
                      :class="p.industry === 'IT' ? 'text-cyan' : 'text-gold'"
                      style="font-size: 0.7rem"
                    >
                      {{ p.industry || 'Specialist' }}
                    </span>
                  </div>
                </div>
                <button
                  class="btn btn-sm btn-outline-light-custom rounded-pill px-3 py-1 text-nowrap ms-3"
                >
                  View Profile
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.text-cyan {
  color: #4da3ff !important;
}
.text-gold {
  color: #ffd200 !important;
}
.btn-outline-light-custom {
  color: rgba(255, 255, 255, 0.7) !important;
  border: 1px solid rgba(255, 255, 255, 0.15) !important;
  font-size: 0.8rem;
  font-weight: 600;
}
.btn-outline-light-custom:hover {
  color: #ffffff !important;
  background-color: rgba(255, 255, 255, 0.1) !important;
  border-color: rgba(255, 255, 255, 0.3) !important;
}

.detail-modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(11, 19, 41, 0.75);
  backdrop-filter: blur(12px);
  z-index: 1050;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
}

.detail-modal-content {
  background: rgba(11, 19, 41, 0.95) !important;
  backdrop-filter: blur(25px);
  border: 1px solid rgba(255, 255, 255, 0.12) !important;
  box-shadow:
    0 25px 60px rgba(0, 0, 0, 0.65),
    0 0 50px rgba(77, 163, 255, 0.1) !important;
  max-width: 600px;
  width: 100%;
  max-height: 85vh;
  overflow-y: auto;
  overflow-x: hidden;
  position: relative;
  border-radius: 24px !important;
  animation: modal-appear 0.35s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.modal-glow-bg {
  position: absolute;
  top: -120px;
  right: -120px;
  width: 300px;
  height: 300px;
  border-radius: 50%;
  filter: blur(90px);
  opacity: 0.18;
  pointer-events: none;
  z-index: 1;
  transition: opacity 0.3s ease;
}
.it-glow {
  background: #4da3ff;
}
.embedded-glow {
  background: #ffd200;
}

@keyframes modal-appear {
  from {
    transform: scale(0.92) translateY(15px);
    opacity: 0;
  }
  to {
    transform: scale(1) translateY(0);
    opacity: 1;
  }
}

.detail-modal-content::-webkit-scrollbar {
  width: 6px;
}
.detail-modal-content::-webkit-scrollbar-track {
  background: rgba(0, 0, 0, 0.05);
  border-radius: 4px;
}
.detail-modal-content::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 4px;
}
.detail-modal-content::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.2);
}

.uppercase-heading {
  font-size: 0.75rem !important;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.45) !important;
}

.badge-skill {
  background-color: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  color: rgba(255, 255, 255, 0.85);
  font-size: 0.75rem;
  padding: 0.25rem 0.6rem;
  border-radius: 6px;
}

.sub-card {
  background-color: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.06);
  cursor: pointer;
  transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
}
.sub-card:hover {
  background-color: rgba(255, 255, 255, 0.07);
  border-color: rgba(255, 255, 255, 0.18);
  transform: translateY(-2px) translateX(2px);
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
}

.cursor-pointer {
  cursor: pointer;
}

.fade-blur-enter-active,
.fade-blur-leave-active {
  transition:
    opacity 0.25s ease,
    backdrop-filter 0.25s ease;
}
.fade-blur-enter-from,
.fade-blur-leave-to {
  opacity: 0;
  backdrop-filter: blur(0px);
}

.modal-description {
  color: rgba(255, 255, 255, 0.95) !important;
  font-size: 0.92rem;
  line-height: 1.6;
}
.gap-2\.5 {
  gap: 0.625rem;
}
</style>

// app/_components/DetailModal.tsx
'use client'

import { useEffect, useRef } from 'react'
import { ExternalLink, X } from 'lucide-react'
import { FaGithub, FaLinkedin, FaYoutube } from 'react-icons/fa'
import type { Participant, Project } from '../_lib/types'
import {
  getProfilePictureUrl,
  getInitials,
  getProjectsForParticipant,
  getParticipantsForProject,
  getYoutubeEmbedUrl,
  getTextClass,
  getIndustryLabel,
} from '../_lib/helpers'
import dynamic from 'next/dynamic'
const FrameworkIcons = dynamic(() => import('./FrameworkIcons'), { ssr: false })

interface DetailModalProps {
  activeModalType: 'person' | 'project' | null
  activeItem: Participant | Project | null
  onClose: () => void
  onShowPerson: (person: Participant) => void
  onShowProject: (project: Project) => void
}

export default function DetailModal({
  activeModalType,
  activeItem,
  onClose,
  onShowPerson,
  onShowProject,
}: DetailModalProps) {
  const overlayRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (activeModalType) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
    }
    return () => { document.body.style.overflow = '' }
  }, [activeModalType])

  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    if (activeModalType) {
      window.addEventListener('keydown', handleEsc)
      return () => window.removeEventListener('keydown', handleEsc)
    }
  }, [activeModalType, onClose])

  if (!activeModalType || !activeItem) return null

  const activeParticipant = activeModalType === 'person' ? (activeItem as Participant) : null
  const activeProject = activeModalType === 'project' ? (activeItem as Project) : null

  return (
    <div
      ref={overlayRef}
      className="detail-modal-overlay"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
    >
      {/* Person Detail Modal */}
      {activeModalType === 'person' && activeParticipant && (
        <div className="detail-modal-content p-4 text-start sm:p-6">
          <button className="btn-close-white" onClick={onClose} aria-label="Close">
            <X size={20} />
          </button>

          {/* M-stripe divider at top */}
          <div className="m-stripe-divider mb-6" />

          {/* Header */}
          <div className="mb-6 flex items-center gap-4">
            <div className="flex-shrink-0" style={{ width: 72, height: 72 }}>
              {activeParticipant.profilePicture ? (
                <img
                  src={getProfilePictureUrl(activeParticipant.profilePicture)}
                  alt={activeParticipant.name}
                  className="border border-hairline object-cover"
                  style={{ width: 72, height: 72 }}
                />
              ) : (
                <div
                  className="flex items-center justify-center border border-hairline font-bold text-on-dark"
                  style={{
                    backgroundColor: 'var(--color-surface-soft)',
                    width: 72,
                    height: 72,
                    fontSize: '1.25rem',
                  }}
                >
                  {getInitials(activeParticipant.name)}
                </div>
              )}
            </div>
            <div>
              <h2 className="mb-2 text-xl font-bold uppercase tracking-tight text-on-dark">
                {activeParticipant.name}
              </h2>
              <span
                className={`badge-m ${getTextClass(activeParticipant.industry)}`}
              >
                {getIndustryLabel(activeParticipant.industry)} Developer
              </span>
            </div>
          </div>

          {/* Social Links */}
          {(activeParticipant.github || activeParticipant.linkedin) && (
            <div className="mb-6 flex gap-3">
              {activeParticipant.github && (
                <a
                  href={activeParticipant.github}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn-sm-m btn-outline-m inline-flex items-center gap-1.5"
                >
                  <FaGithub className="inline" />
                  GitHub
                </a>
              )}
              {activeParticipant.linkedin && (
                <a
                  href={activeParticipant.linkedin}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn-sm-m btn-outline-m inline-flex items-center gap-1.5"
                >
                  <FaLinkedin className="inline" />
                  LinkedIn
                </a>
              )}
            </div>
          )}

          {/* Bio */}
          <div className="mb-6">
            <h3 className="uppercase-heading mb-3">Biography</h3>
            <p className="text-sm text-body leading-relaxed">{activeParticipant.description}</p>
          </div>

          {/* Skills */}
          <div className="mb-6">
            <h3 className="uppercase-heading mb-3">Skills &amp; Expertise</h3>
            <div className="flex flex-wrap gap-2">
              {activeParticipant.skills.map((skill) => (
                <span key={skill} className="skill-chip">
                  {skill}
                </span>
              ))}
            </div>
          </div>

          {/* Framework Icons */}
          <div className="mb-6">
            <h3 className="uppercase-heading mb-3">Technologies Detected</h3>
            <FrameworkIcons
              skills={activeParticipant.skills}
              description={activeParticipant.description}
            />
          </div>

          {/* Projects */}
          <div>
            <h3 className="uppercase-heading mb-4">Assigned Projects</h3>
            <div className="flex flex-col gap-2">
              {getProjectsForParticipant(activeParticipant.id).map((proj) => (
                <div
                  key={proj.id}
                  className="sub-card flex cursor-pointer items-center justify-between p-4"
                  onClick={() => onShowProject(proj)}
                >
                  <div>
                    <h4 className="mb-1 text-sm font-bold text-on-dark">{proj.title}</h4>
                    <span
                      className={`text-xs font-bold uppercase tracking-[1.5px] ${
                        proj.category.includes('IT') ? 'text-cyan' : 'text-gold'
                      }`}
                    >
                      {proj.category}
                    </span>
                  </div>
                  <span className="ms-4 whitespace-nowrap text-xs font-bold uppercase tracking-[1.5px] text-muted hover:text-on-dark">
                    View &rarr;
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Project Detail Modal */}
      {activeModalType === 'project' && activeProject && (
        <div className="detail-modal-content p-4 text-start sm:p-6">
          <button className="btn-close-white" onClick={onClose} aria-label="Close">
            <X size={20} />
          </button>

          {/* M-stripe divider at top */}
          <div className="m-stripe-divider mb-6" />

          {/* Header */}
          <div className="mb-6">
            <span
              className={`badge-m mb-3 inline-block ${
                activeProject.category.includes('IT')
                  ? 'text-cyan'
                  : 'text-gold'
              }`}
            >
              {activeProject.category} Project
            </span>
            <h2 className="mb-0 text-xl font-bold uppercase tracking-tight text-on-dark">
              {activeProject.title}
            </h2>
          </div>

          {/* Project Links */}
          <div className="mb-6 flex flex-wrap gap-3">
            {activeProject.github && (
              <a
                href={activeProject.github}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-sm-m btn-outline-m inline-flex items-center gap-1.5"
              >
                <FaGithub className="inline" />
                Source Code
              </a>
            )}
            {activeProject.demo && (
              <a
                href={activeProject.demo}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-sm-m btn-outline-m inline-flex items-center gap-1.5"
              >
                <ExternalLink size={14} />
                Live Demo
              </a>
            )}
          </div>

          {/* Media Gallery */}
          {activeProject.media && activeProject.media.length > 0 && (
            <div className="mb-6">
              <h3 className="uppercase-heading mb-3">Media</h3>
              <div className="flex flex-col gap-3">
                {activeProject.media.map((item, i) => (
                  <div key={i} className="border border-hairline bg-surface-soft">
                    {item.type === 'youtube' ? (
                      <div className="relative" style={{ paddingBottom: '56.25%' }}>
                        <iframe
                          src={getYoutubeEmbedUrl(item.url)}
                          className="absolute inset-0 h-full w-full"
                          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                          allowFullScreen
                          title={item.caption || `Video ${i + 1}`}
                        />
                      </div>
                    ) : item.type === 'linkedin' ? (
                      <a
                        href={item.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-3 p-4 transition-colors hover:bg-surface-card"
                      >
                        <FaLinkedin className="flex-shrink-0 text-tb-cyan" />
                        <div>
                          <p className="text-sm font-bold text-on-dark">
                            {item.caption || 'LinkedIn Post'}
                          </p>
                          <p className="text-xs text-muted">View on LinkedIn &rarr;</p>
                        </div>
                      </a>
                    ) : (
                      <img
                        src={item.url}
                        alt={item.caption || `Image ${i + 1}`}
                        className="w-full object-cover"
                        style={{ maxHeight: 400 }}
                      />
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Description */}
          <div className="mb-6">
            <h3 className="uppercase-heading mb-3">Project Overview</h3>
            <p className="text-sm text-body leading-relaxed">{activeProject.description}</p>
          </div>

          {/* Tech Used */}
          <div className="mb-6">
            <h3 className="uppercase-heading mb-3">Technologies Used</h3>
            <div className="flex flex-wrap gap-2">
              {activeProject.skills.map((skill) => (
                <span key={skill} className="skill-chip">
                  {skill}
                </span>
              ))}
            </div>
          </div>

          {/* Framework Icons */}
          <div className="mb-6">
            <h3 className="uppercase-heading mb-3">Framework Detection</h3>
            <FrameworkIcons
              skills={activeProject.skills}
              description={activeProject.description}
              tags={activeProject.tags}
            />
          </div>

          {/* Team */}
          <div>
            <h3 className="uppercase-heading mb-4">Project Team</h3>
            <div className="flex flex-col gap-2">
              {getParticipantsForProject(activeProject.id).map((p) => (
                <div
                  key={p.id}
                  className="sub-card flex cursor-pointer items-center justify-between p-4"
                  onClick={() => onShowPerson(p)}
                >
                  <div className="flex items-center gap-3">
                    {p.profilePicture ? (
                      <img
                        src={getProfilePictureUrl(p.profilePicture)}
                        alt={p.name}
                        className="flex-shrink-0 border border-hairline object-cover"
                        style={{ width: 40, height: 40 }}
                      />
                    ) : (
                      <div
                        className="flex flex-shrink-0 items-center justify-center border border-hairline font-bold text-on-dark"
                        style={{
                          backgroundColor: 'var(--color-surface-soft)',
                          width: 40,
                          height: 40,
                          fontSize: '0.85rem',
                        }}
                      >
                        {getInitials(p.name)}
                      </div>
                    )}
                    <div>
                      <h4 className="mb-0 text-sm font-bold text-on-dark">{p.name}</h4>
                      <span
                        className={`text-xs font-bold uppercase tracking-[1.5px] ${getTextClass(p.industry)}`}
                      >
                        {getIndustryLabel(p.industry)}
                      </span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {p.github && (
                      <a
                        href={p.github}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-muted transition-colors hover:text-on-dark"
                        onClick={(e) => e.stopPropagation()}
                      >
                        <FaGithub className="inline" />
                      </a>
                    )}
                    {p.linkedin && (
                      <a
                        href={p.linkedin}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-muted transition-colors hover:text-on-dark"
                        onClick={(e) => e.stopPropagation()}
                      >
                        <FaLinkedin className="inline" />
                      </a>
                    )}
                    <span className="whitespace-nowrap text-xs font-bold uppercase tracking-[1.5px] text-muted hover:text-on-dark">
                      View &rarr;
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
