// src/components/Footer.vue
<template>
  <footer
    class="py-4 text-light border-top border-white border-opacity-10"
    style="background-color: #03234b"
  >
    <div class="container">
      <div class="row align-items-center gy-3">
        <!-- Left: Logo and Brand (Matching Navbar) -->
        <div class="col-md-4 text-center text-md-start">
          <RouterLink class="d-inline-flex align-items-center text-decoration-none" to="/">
            <img
              src="../static/ST_logo_2024_blue.jpg"
              alt="STMicroelectronics"
              class="object-fit-contain"
              style="height: 2rem"
            />
            <span class="ms-2 text-white fs-5"><b>TechBlazers</b></span>
          </RouterLink>
        </div>

        <!-- Middle: Compact Quick Links -->
        <div class="col-md-4 text-center">
          <div class="d-flex justify-content-center gap-3 align-items-center">
            <RouterLink to="/" class="text-decoration-none small text-white-50 link-light"
              >Home</RouterLink
            >
            <span class="text-white-50 opacity-25 small">•</span>
            <RouterLink to="/projects" class="text-decoration-none small text-white-50 link-light"
              >Projects</RouterLink
            >
            <span class="text-white-50 opacity-25 small">•</span>
            <RouterLink to="/people" class="text-decoration-none small text-white-50 link-light"
              >People</RouterLink
            >
          </div>
        </div>

        <!-- Right: Compact Socials (Bigger Icons) -->
        <div class="col-md-4 text-center text-md-end">
          <div class="d-inline-flex gap-3">
            <a
              href="https://github.com/techblazers"
              target="_blank"
              class="text-white-50 link-light d-inline-flex align-items-center justify-content-center"
              aria-label="GitHub"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                class="bi bi-github"
                viewBox="0 0 16 16"
              >
                <path
                  d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"
                />
              </svg>
            </a>
            <a
              href="https://www.linkedin.com/company/stmicroelectronics/"
              target="_blank"
              class="text-white-50 link-light d-inline-flex align-items-center justify-content-center"
              aria-label="LinkedIn"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                class="bi bi-linkedin"
                viewBox="0 0 16 16"
              >
                <path
                  d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.145 2.4 3.855c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"
                />
              </svg>
            </a>
            <a
              href="https://www.instagram.com/stmicroelectronics.nv/"
              target="_blank"
              class="text-white-50 link-light d-inline-flex align-items-center justify-content-center"
              aria-label="Instagram"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                class="bi bi-instagram"
                viewBox="0 0 16 16"
              >
                <path
                  d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"
                />
              </svg>
            </a>
            <a
              href="https://x.com/ST_World"
              target="_blank"
              class="text-white-50 link-light d-inline-flex align-items-center justify-content-center"
              aria-label="X"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                class="bi bi-twitter-x"
                viewBox="0 0 16 16"
              >
                <path
                  d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"
                />
              </svg>
            </a>
          </div>
        </div>
      </div>

      <!-- Divider Line -->
      <hr class="my-3 border-top border-white border-opacity-10" />

      <!-- Bottom Row -->
      <div class="row align-items-center gy-2">
        <div class="col-sm-6 text-center text-sm-start">
          <p class="text-white-50 small mb-0">&copy; 2025 Techblazers. All rights reserved.</p>
        </div>
        <div class="col-sm-6 text-center text-sm-end">
          <p class="text-white-50 small mb-0">
            Designed by
            <a
              href="https://github.com/Aryan-Maini"
              target="_blank"
              class="link-info fw-semibold text-decoration-none"
              >Aryan Maini</a
            >
          </p>
        </div>
      </div>
    </div>
  </footer>
</template>

// app/_components/Footer.tsx
import Link from 'next/link'

function FooterMStripe() {
  return (
    <svg
      className="m-stripe-svg block w-full"
      viewBox="0 0 1440 4"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      preserveAspectRatio="none"
      style={{ height: 4 }}
    >
      <path d="M0 0.667h1440" stroke="var(--color-m-blue-light)" strokeWidth="1.33"
        style={{ strokeDasharray: 1440, strokeDashoffset: 1440 }} />
      <path d="M0 2h1440" stroke="var(--color-m-blue-dark)" strokeWidth="1.33"
        style={{ strokeDasharray: 1440, strokeDashoffset: 1440 }} />
      <path d="M0 3.333h1440" stroke="var(--color-m-red)" strokeWidth="1.33"
        style={{ strokeDasharray: 1440, strokeDashoffset: 1440 }} />
    </svg>
  )
}

export default function Footer() {
  const year = new Date().getFullYear()

  return (
    <footer className="bg-canvas border-t border-hairline">
      <div className="m-stripe-divider" />
      <div className="mx-auto max-w-[1440px] px-4 py-12 sm:px-6 sm:py-16">
        <div className="flex flex-col items-start justify-between gap-8 md:flex-row md:items-center">
          {/* Left: Logo and Brand */}
          <div>
            <Link href="/" className="inline-flex items-center gap-3 text-decoration-none">
              <img
                src="/ST_logo_2024_blue.jpg"
                alt="STMicroelectronics"
                className="object-contain"
                style={{ height: '1.5rem' }}
              />
              <span className="text-sm font-bold uppercase tracking-[1.5px] text-on-dark">
                TechBlazers
              </span>
            </Link>
          </div>

          {/* Middle: Quick Links */}
          <div className="flex items-center gap-6">
            {['Home', 'Projects', 'People'].map((label, i) => (
              <Link
                key={label}
                href={i === 0 ? '/' : `/${label.toLowerCase()}`}
                className="text-sm text-muted hover:text-on-dark tracking-[0.5px] text-decoration-none transition-colors"
              >
                {label}
              </Link>
            ))}
          </div>

          {/* Right: Socials */}
          <div className="flex items-center gap-4">
            {[
              { href: 'https://github.com/techblazers', label: 'GitHub', path: 'M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8' },
              { href: 'https://www.linkedin.com/company/stmicroelectronics/', label: 'LinkedIn', path: 'M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.145 2.4 3.855c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z' },
              { href: 'https://www.instagram.com/stmicroelectronics.nv/', label: 'Instagram', path: 'M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334' },
              { href: 'https://x.com/ST_World', label: 'X', path: 'M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z' },
            ].map(({ href, label, path }) => (
              <a
                key={label}
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted hover:text-on-dark transition-colors"
                aria-label={label}
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                  <path d={path} />
                </svg>
              </a>
            ))}
          </div>
        </div>

        {/* Bottom Row */}
        <div className="mt-8 flex flex-col items-start justify-between gap-2 border-t border-hairline pt-8 sm:flex-row">
          <p className="text-sm text-muted">
            &copy; {year} TechBlazers. All rights reserved.
          </p>
          <p className="text-sm text-muted">
            Designed &amp; Built by{' '}
            <a
              href="https://github.com/TejasLamba2006"
              target="_blank"
              rel="noopener noreferrer"
              className="text-on-dark text-decoration-none transition-colors hover:text-tb-cyan"
            >
              Tejas Lamba
            </a>
          </p>
        </div>
      </div>
    </footer>
  )
}
