// src/pages/People.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Participant } from '../types'
import participantsData from '../static/participants.json'
import { shuffleArray } from '../utils/helpers'
import { useModalDetails } from '../composables/useModalDetails'
import ParticipantCard from '../components/ParticipantCard.vue'
import DetailModal from '../components/DetailModal.vue'

const selectedIndustry = ref('All')

const participants = ref<Participant[]>(shuffleArray(participantsData))

const filteredParticipants = computed(() => {
  return participants.value.filter((p) => {
    return selectedIndustry.value === 'All' || p.industry === selectedIndustry.value
  })
})

const {
  activeModalType,
  activeItem,
  showParticipantDetails,
  showProjectDetails,
  closeDetails
} = useModalDetails()
</script>

<template>
  <div class="py-5 text-light min-vh-100" style="background-color: transparent">
    <div class="container py-4">
      <!-- Hero & Header Section -->
      <section class="mb-5 text-center">
        <div class="d-flex flex-column gap-2 mb-4">
          <h1 class="display-6 fw-bold text-white tracking-tight">TechBlazers Directory</h1>
          <p class="text-white-50 lead fs-6 mx-auto" style="max-width: 500px">
            Meet the innovative minds and tech pioneers driving our program forward.
          </p>
        </div>

        <!-- Simple Filter Tabs (Pill Buttons) -->
        <div class="d-flex justify-content-center gap-2 mb-4">
          <button
            @click="selectedIndustry = 'All'"
            class="btn rounded-pill px-4 py-2 small fw-semibold transition-all shadow-none"
            :class="
              selectedIndustry === 'All'
                ? 'btn-primary bg-primary border-primary'
                : 'btn-outline-light text-white-50 border-white-opacity-10'
            "
          >
            All
          </button>
          <button
            @click="selectedIndustry = 'IT'"
            class="btn rounded-pill px-4 py-2 small fw-semibold transition-all shadow-none"
            :class="
              selectedIndustry === 'IT'
                ? 'btn-primary bg-primary border-primary'
                : 'btn-outline-light text-white-50 border-white-opacity-10'
            "
          >
            IT
          </button>
          <button
            @click="selectedIndustry = 'Embedded'"
            class="btn rounded-pill px-4 py-2 small fw-semibold transition-all shadow-none"
            :class="
              selectedIndustry === 'Embedded'
                ? 'btn-primary bg-primary border-primary'
                : 'btn-outline-light text-white-50 border-white-opacity-10'
            "
          >
            Embedded
          </button>
        </div>
      </section>

      <!-- Minimalist Team Grid -->
      <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 mb-4">
        <div v-for="(p, index) in filteredParticipants" :key="index" class="col">
          <ParticipantCard :participant="p" @click="showParticipantDetails(p)" />
        </div>
      </div>

      <!-- Empty State -->
      <div v-if="filteredParticipants.length === 0" class="text-center py-5">
        <p class="text-white-50 fs-5">No participants found matching this category.</p>
      </div>
    </div>

    <!-- Detail Modal -->
    <DetailModal
      :active-modal-type="activeModalType"
      :active-item="activeItem"
      @close="closeDetails"
      @show-person="showParticipantDetails"
      @show-project="showProjectDetails"
    />
  </div>
</template>

<style scoped>
.border-white-opacity-10 {
  border-color: rgba(255, 255, 255, 0.1) !important;
}
.btn-outline-light {
  border-color: rgba(255, 255, 255, 0.1);
}
.btn-outline-light:hover {
  background-color: rgba(255, 255, 255, 0.1);
  color: #ffffff !important;
}
</style>

// app/people/page.tsx
'use client'

import { useState, useMemo } from 'react'
import type { Participant } from '../_lib/types'
import { participants } from '../_lib/data'
import { shuffleArray } from '../_lib/helpers'
import { useModalDetails } from '../_hooks/useModalDetails'
import { useScrollReveal } from '../_hooks/useScrollReveal'
import ParticipantCard from '../_components/ParticipantCard'
import DetailModal from '../_components/DetailModal'

const shuffledParticipants = shuffleArray(participants) as Participant[]

const industries = ['All', 'IT', 'Embedded']

export default function PeoplePage() {
  const [selectedIndustry, setSelectedIndustry] = useState('All')
  const containerRef = useScrollReveal()

  const filteredParticipants = useMemo(() => {
    return shuffledParticipants.filter((p) => {
      return selectedIndustry === 'All' || p.industry.includes(selectedIndustry)
    })
  }, [selectedIndustry])

  const {
    activeModalType,
    activeItem,
    showParticipantDetails,
    showProjectDetails,
    closeDetails,
  } = useModalDetails()

  return (
    <div ref={containerRef} className="min-h-screen text-body">
      <div className="mx-auto max-w-[1440px] px-4 py-12 sm:px-6 sm:py-16 md:py-24">
        {/* Hero */}
        <section className="mb-10 sm:mb-16">
          <h1 className="mb-4 text-3xl font-bold uppercase tracking-tight text-on-dark anim-fade-up sm:text-4xl md:text-6xl">
            Directory
          </h1>
          <p className="max-w-[500px] text-sm font-light text-body anim-fade-up sm:text-base">
            Meet the innovative minds and tech pioneers driving our program forward.
          </p>
        </section>

        {/* Filter Tabs */}
        <div className="mb-8 flex gap-0 border-b border-hairline sm:mb-12 anim-fade-up">
          {industries.map((ind) => (
            <button
              key={ind}
              onClick={() => setSelectedIndustry(ind)}
              className={`filter-tab ${selectedIndustry === ind ? 'filter-tab-active' : ''}`}
            >
              {ind}
            </button>
          ))}
        </div>

        {/* Team Grid — alternating slide-in */}
        <div className="grid grid-cols-1 gap-px sm:grid-cols-2 lg:grid-cols-3 tilt-container">
          {filteredParticipants.map((p, index) => (
            <div
              key={p.id}
              className={index % 2 === 0 ? 'anim-slide-right' : 'anim-slide-left'}
              style={{ animationDelay: `${(index % 6) * 80}ms` } as React.CSSProperties}
            >
              <ParticipantCard
                participant={p}
                onClick={() => showParticipantDetails(p)}
                index={index}
              />
            </div>
          ))}
        </div>

        {/* Empty State */}
        {filteredParticipants.length === 0 && (
          <div className="py-16 text-center sm:py-24">
            <p className="text-base text-muted sm:text-lg">No participants found matching this industry.</p>
          </div>
        )}
      </div>

      {/* Detail Modal */}
      <DetailModal
        activeModalType={activeModalType}
        activeItem={activeItem}
        onClose={closeDetails}
        onShowPerson={showParticipantDetails}
        onShowProject={showProjectDetails}
      />
    </div>
  )
}
